language: python
env:
  global:
  - secure: bCrXmS1k8aIOE8Ba6XuHyjUoQQPpYEC8kpTcMi9pNhyXRQyGEPLp85VgyfXga2Oxb73QcW1aW4AxGUxiR1OZjB4rBmKK2uKij2G2qq9uhcXkDqCzqqxslhtm3o8cxHEFNJWRhuSVVjS0m0RvaFuGRicdz7QdyHCLl29+Gqdkacs=
  - secure: W81QkyB8I87JT6kqaW/eBYBngbtcpHXWXIQsBkjy06Z8V9gUGbUD5oWwCn6NKQ1hE1ZR/qELxsTtrfgvfiegCW9wci4qZzatq34DWvzKK20jacqn9hs0BnXCyI/+iQRf6vam1KAnvc4qmWzF/CfsuZqCku8TtU5ZtKk05D/K//0=
matrix:
  include:
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--python-tag py27"
  - python: 3.3
    env:
    - BOB_UPLOAD_WHEEL="--python-tag py3"
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libfreetype6-dev libboost-all-dev libblitz1-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --upgrade pip
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose --pre coverage==3.7.1 coveralls bob.blitz
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:prefer-final=true
script:
- ./bin/python -c 'from bob.extension import get_config; print(get_config())'
- ./bin/coverage run --source=bob.extension ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- ./scripts/upload-sphinx.sh
- ./scripts/upload-wheel.sh
