{% set name = 'bob.extension' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - click {{ click }}
    - click-plugins {{ click_plugins }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('click') }}
    - {{ pin_compatible('click-plugins') }}

test:
  imports:
    - {{ name }}
  commands:
    - bob -h
    - bob --help
    - bob config -h
    - bob config --help
    # fix for the CONDA_BUILD_SYSROOT variable missing at test time
    - export CONDA_BUILD_SYSROOT={{ CONDA_BUILD_SYSROOT }}  # [osx]
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - boost
    - cmake
    - make
    - pkg-config
    - freetype
    - libblitz
    - numpy
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Building of Python/C++ extensions for Bob
  license_family: BSD
