{% set name = 'bob.extension' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - "{{ PYTHON }} setup.py sdist --formats=zip"
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - click >=8
    - click {{ click }}
    - click-plugins {{ click_plugins }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('click') }}
    - {{ pin_compatible('click-plugins') }}

test:
  imports:
    - {{ name }}
  commands:
    - bob -h
    - bob --help
    - bob config -h
    - bob config --help
    # fix for the CONDA_BUILD_SYSROOT variable missing at test time
    - export CONDA_BUILD_SYSROOT={{ CONDA_BUILD_SYSROOT }}  # [osx]
    - pytest --verbose --cov {{ name }} --cov-report term-missing --cov-report html:{{ project_dir }}/sphinx/coverage --cov-report xml:{{ project_dir }}/coverage.xml --pyargs {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - pytest {{ pytest }}
    - pytest-cov {{ pytest_cov }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - numpy {{ numpy }}

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Building of Python/C++ extensions for Bob
  license_family: BSD
